spring:
  application:
    name: patient-microservice
server:
  port: 8081

#Register with Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#Resilience4J
resilience4j:
  circuitbreaker:
    instances:
      getAllServicesBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED